# Generated by Django 3.2.6 on 2021-10-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionTracker', '0011_auto_20210905_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='İsim')),
                ('question', models.PositiveIntegerField(verbose_name='Soru Sayısı')),
                ('minute', models.IntegerField(verbose_name='Dakika')),
                ('second', models.IntegerField(verbose_name='Saniye')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Tarih')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionTracker.area', verbose_name='Alan')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.lesson', verbose_name='Ders')),
            ],
        ),
    ]
