# Generated by Django 3.2.6 on 2021-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronometer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronometer',
            name='false',
            field=models.IntegerField(default=0, verbose_name='Yanlış Soru'),
        ),
        migrations.AddField(
            model_name='chronometer',
            name='true',
            field=models.IntegerField(default=0, verbose_name='Doğru Soru'),
        ),
    ]
