# Generated by Django 3.2.4 on 2021-06-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Süre')),
            ],
        ),
    ]
