# Generated by Django 3.2.4 on 2021-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time',
        ),
        migrations.AddField(
            model_name='time',
            name='hour',
            field=models.IntegerField(default=1, verbose_name='Saat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='minute',
            field=models.IntegerField(default=1, verbose_name='Dakika'),
            preserve_default=False,
        ),
    ]
