# Generated by Django 3.1.5 on 2021-07-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0006_auto_20210626_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarih'),
        ),
    ]
