# Generated by Django 3.1.5 on 2021-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0008_auto_20210704_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarih'),
        ),
    ]
