# Generated by Django 3.2.4 on 2021-06-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionTracker', '0003_alter_question_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Isim')),
                ('status', models.CharField(choices=[('Hayır', 'Hayır'), ('Doğru', 'Doğru')], max_length=255, verbose_name='Durum')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.area', verbose_name='Alan')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.class', verbose_name='Sınıf')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.lesson', verbose_name='Ders')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectTracker.subject', verbose_name='Konu')),
            ],
        ),
    ]
