# Generated by Django 3.2.4 on 2021-06-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjectTracker', '0005_auto_20210625_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='subjectTracker.subject', verbose_name='Parent'),
        ),
    ]
