# Generated by Django 3.2.4 on 2021-06-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('text', models.CharField(max_length=255, verbose_name='Yapılacak Is')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='Durum')),
            ],
        ),
    ]
