# Generated by Django 3.2.4 on 2021-06-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tarih'),
        ),
    ]
