# Generated by Django 3.2.4 on 2021-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarih'),
        ),
    ]
