# Generated by Django 3.2.4 on 2021-06-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionTracker', '0006_auto_20210625_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='İsim')),
                ('total_question', models.PositiveIntegerField(verbose_name='Soru Sayısı')),
                ('true_question', models.PositiveIntegerField(verbose_name='Doğru Soru Sayısı')),
                ('false_question', models.PositiveIntegerField(verbose_name='Yanlış Soru Sayısı')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Tarih')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.area', verbose_name='Alan')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.class', verbose_name='Sınıf')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.lesson', verbose_name='Ders')),
            ],
        ),
    ]
