# Generated by Django 3.2.4 on 2021-06-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionTracker', '0006_auto_20210625_1906'),
        ('testTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='İsim')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Tarih')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.area', verbose_name='Alan')),
            ],
        ),
        migrations.AddField(
            model_name='branchtest',
            name='area_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testTracker.areatest'),
        ),
    ]
