# Generated by Django 3.2.4 on 2021-06-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionTracker', '0006_auto_20210625_1906'),
        ('testTracker', '0002_auto_20210625_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchtest',
            name='area',
        ),
        migrations.RemoveField(
            model_name='branchtest',
            name='clas',
        ),
        migrations.CreateModel(
            name='LessonForTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='İsim')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.area', verbose_name='Alan')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.class', verbose_name='Sınıf')),
            ],
        ),
        migrations.AlterField(
            model_name='branchtest',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testTracker.lessonfortest', verbose_name='Ders'),
        ),
    ]
