# Generated by Django 3.2.4 on 2021-06-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testTracker', '0003_auto_20210625_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonfortest',
            name='clas',
        ),
    ]
