# Generated by Django 3.2.4 on 2021-06-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testTracker', '0004_remove_lessonfortest_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtest',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testTracker.lessonfortest', verbose_name='Ders'),
        ),
    ]
