# Generated by Django 3.2.4 on 2021-06-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionTracker', '0006_auto_20210625_1906'),
        ('testTracker', '0005_alter_branchtest_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtest',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionTracker.area', verbose_name='Alan'),
        ),
        migrations.AddField(
            model_name='branchtest',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionTracker.class', verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='branchtest',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.lesson', verbose_name='Ders'),
        ),
        migrations.DeleteModel(
            name='LessonForTest',
        ),
    ]
