# Generated by Django 3.2.6 on 2021-10-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTracker', '0008_auto_20210905_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatest',
            name='date',
            field=models.DateTimeField(verbose_name='Tarih'),
        ),
    ]
