# Generated by Django 3.2.6 on 2021-10-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTracker', '0009_alter_areatest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
    ]
