# Generated by Django 3.2.6 on 2021-11-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTracker', '0010_alter_areatest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatest',
            name='date',
            field=models.DateTimeField(verbose_name='Tarih'),
        ),
    ]
