# Generated by Django 4.0.2 on 2022-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTracker', '0012_areatest_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatest',
            name='visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Görünürlük'),
        ),
    ]
