# Generated by Django 3.2.6 on 2021-10-28 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Tarih'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('False', 'Yanlış'), ('Blank', 'Boş'), ('SSA solved', 'KÇS çözüldü'), ('solved', 'çözüldü')], default=1, max_length=255, verbose_name='Durum'),
            preserve_default=False,
        ),
    ]
