# Generated by Django 3.2.6 on 2021-10-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.status'),
        ),
    ]
