# Generated by Django 3.2.4 on 2021-06-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Isim')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Isim')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Isim')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Isim')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionTracker.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Isim')),
                ('count', models.IntegerField(verbose_name='Soru Sayısı')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.area', verbose_name='Alan')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.class', verbose_name='Sınıf')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.lesson', verbose_name='Ders')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionTracker.subject', unique=True, verbose_name='Konu')),
            ],
        ),
    ]
