# Generated by Django 3.2.4 on 2021-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarih'),
        ),
    ]
