# Generated by Django 3.1.5 on 2021-06-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionTracker', '0007_auto_20210626_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionTracker.subject', verbose_name='Konu'),
        ),
    ]
