# Generated by Django 3.1.5 on 2021-06-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionTracker', '0008_auto_20210626_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
