# Generated by Django 3.1.5 on 2021-06-29 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionTracker', '0009_auto_20210626_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionTracker.class', verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionTracker.lesson', verbose_name='Ders'),
        ),
    ]
